
import type { Project, Task, Sprint } from '@/types';
import { FileText, Code, Home } from 'lucide-react';

export const projects: Project[] = [
  { id: 'PROJ-1', name: 'Website Redesign', icon: Home },
  { id: 'PROJ-2', name: 'API Integration', icon: Code },
  { id: 'PROJ-3', name: 'Documentation', icon: FileText },
];

export const sprints: Sprint[] = [
  {
    id: 'SPR-1',
    name: 'August Sprint #1 (2024)',
    status: 'active',
    goal: 'Launch V2 of the marketing website and improve performance by 15%.',
    startDate: new Date('2024-08-01T00:00:00.000Z'),
    endDate: new Date('2024-08-14T23:59:59.000Z'),
    organizationId: 'default-org',
    createdBy: 'user-1',
  },
  {
    id: 'SPR-2',
    name: 'July Sprint #2 (2024)',
    status: 'completed',
    goal: 'Complete the API integration with the new payment provider.',
    startDate: new Date('2024-07-15T00:00:00.000Z'),
    endDate: new Date('2024-07-31T23:59:59.000Z'),
    organizationId: 'default-org',
    createdBy: 'user-1',
  },
  {
    id: 'SPR-3',
    name: 'August Sprint #2 (2024)',
    status: 'planning',
    goal: 'Develop the initial draft of the public API documentation.',
    startDate: new Date('2024-08-15T00:00:00.000Z'),
    endDate: new Date('2024-08-30T23:59:59.000Z'),
    organizationId: 'default-org',
    createdBy: 'user-2',
  },
    {
    id: 'SPR-4',
    name: 'July Sprint #1 (2024)',
    status: 'completed',
    goal: 'Redesign the main dashboard and user profile pages.',
    startDate: new Date('2024-07-01T00:00:00.000Z'),
    endDate: new Date('2024-07-14T23:59:59.000Z'),
    organizationId: 'default-org',
    createdBy: 'user-1',
  },
];


export const tasks: Task[] = [
  {
    id: 'TASK-8782',
    title: 'Deploy to production',
    status: 'todo',
    priority: 'medium',
    project: 'Website Redesign',
    sprintId: 'SPR-1',
    dueDate: '2024-08-15',
  },
  {
    id: 'TASK-7878',
    title: 'Fix authentication bug',
    status: 'in-progress',
    priority: 'high',
    project: 'API Integration',
    sprintId: 'SPR-1',
    dueDate: '2024-08-01',
  },
  {
    id: 'TASK-4567',
    title: 'Design new landing page',
    status: 'done',
    priority: 'medium',
    project: 'Website Redesign',
    sprintId: 'SPR-2',
    dueDate: '2024-07-20',
  },
  {
    id: 'TASK-2345',
    title: 'Write API documentation',
    status: 'canceled',
    priority: 'low',
    project: 'Documentation',
    sprintId: 'SPR-3',
    dueDate: '2024-07-30',
  },
  {
    id: 'TASK-9876',
    title: 'Implement user profile page',
    status: 'todo',
    priority: 'high',
    project: 'Website Redesign',
    sprintId: 'SPR-1',
    dueDate: '2024-09-01',
  },
  {
    id: 'TASK-5432',
    title: 'Set up CI/CD pipeline',
    status: 'in-progress',
    priority: 'high',
    project: 'API Integration',
    sprintId: 'SPR-1',
    dueDate: '2024-08-10',
  },
  {
    id: 'TASK-1011',
    title: 'Update component library',
    status: 'done',
    priority: 'low',
    project: 'Website Redesign',
    sprintId: 'SPR-2',
    dueDate: '2024-07-15',
  },
  {
    id: 'TASK-1213',
    title: 'Onboard new developer',
    status: 'todo',
    priority: 'medium',
    project: 'API Integration',
    sprintId: 'SPR-3',
    dueDate: '2024-08-05',
  },
  {
    id: 'TASK-1415',
    title: 'Review analytics data',
    status: 'in-progress',
    priority: 'low',
    project: 'Website Redesign',
    sprintId: 'SPR-2',
    dueDate: '2024-07-28',
  },
  {
    id: 'TASK-1617',
    title: 'Create getting started guide',
    status: 'todo',
    priority: 'medium',
    project: 'Documentation',
    sprintId: 'SPR-3',
    dueDate: '2024-09-15',
  },
];
